[package]
name = "LightSetter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
json = "0.12.4"
reqwest = "0.8.3"

[[bin]]
name = "LightSetter"
path = "main.rs"
